### ISSUE TITLE
write tests for year impl

### ISSUE THREAD

**Issue by Yczar** [Yczar/chance-dart#132]

**Comment by Sir-Nath** [comment]
I tried running a test for year implementation but it failed and when i manually checked the year method is not returning the expected result.

I ran this;
void main(List<String> args) {
  print(year());
}

Instead of getting the expected minimum to be 1701, i got result below this.


how do I deal with situations like this please

**Comment by Yczar** [comment]
You can try fixing the year to return an expected result @Sir-Nath ... I would review once a PR is created
